name: nextchat
description: Messages social network.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gradient_text: ^1.0.2
  http: ^0.12.2
  intl: ^0.17.0-nullsafety.2
  path: ^1.7.0
  sqflite: ^1.3.2+3
  web_socket_channel: ^1.2.0
  flutter_svg: ^0.20.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/solid/
    - assets/icons/outline/
    - assets/images/
